name: Python CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set environment for UTF-8
      run: |
        export PYTHONIOENCODING=utf-8
    - name: Run unit tests for data service
      run: python -m unittest discover -s tests -p 'test_data.py'
    - name: Run unit tests for app
      run: python -m unittest discover -s tests -p 'test_app.py'
    - name: Generate result file
      run: python app.py --auto > result.txt
    - name: Save result as artifact
      uses: actions/upload-artifact@v2
      with:
        name: result
        path: result.txt